version: 0.2

phases:
  install:
    commands:
      - cd client
      - npm install -g pnpm
      - pnpm install
  pre_build:
    commands:
      - node src/converter/csv/csvToTs.js
  build:
    commands:
      - pnpm run build

artifacts:
  files:
    - '**/*'
  base-directory: 'client/dist'

cache:
  paths:
    - node_modules/**/*
