ALTER TABLE users
    ADD COLUMN deleted_at TIMESTAMP DEFAULT NULL;
ALTER TABLE moments
    ADD COLUMN deleted_at TIMESTAMP DEFAULT NULL;
ALTER TABLE comments
    ADD COLUMN deleted_at TIMESTAMP DEFAULT NULL;
ALTER TABLE echos
    ADD COLUMN deleted_at TIMESTAMP DEFAULT NULL;
ALTER TABLE reward_history
    ADD COLUMN deleted_at TIMESTAMP DEFAULT NULL;
ALTER TABLE notifications
    ADD COLUMN deleted_at TIMESTAMP DEFAULT NULL;
