services:
  app:
    container_name: moment-app-server
    image: skyrockets/moment:${IMAGE_TAG}
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/moment/logs:/app/logs
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      FLYWAY_DB_USER: ${FLYWAY_DB_USER}
      FLYWAY_DB_PASSWORD: ${FLYWAY_DB_PASSWORD}
      JWT_ACCESS_SECRET_KEY: ${JWT_ACCESS_SECRET_KEY}
      JWT_REFRESH_SECRET_KEY: ${JWT_REFRESH_SECRET_KEY}
      ACCESS_TOKEN_EXPIRATION_TIME: ${ACCESS_TOKEN_EXPIRATION_TIME}
      REFRESH_TOKEN_EXPIRATION_TIME: ${REFRESH_TOKEN_EXPIRATION_TIME}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_EMAIL_ACCOUNT: ${GOOGLE_EMAIL_ACCOUNT}
      GOOGLE_EMAIL_PASSWORD: ${GOOGLE_EMAIL_PASSWORD}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_PROD_BUCKET_PATH: ${S3_PROD_BUCKET_PATH}
      S3_DEV_BUCKET_PATH: ${S3_DEV_BUCKET_PATH}
      FCM_CREDENTIALS: ${FCM_CREDENTIALS}
