package moment.report.domain;

public enum ReportReason {

    SPAM_OR_ADVERTISEMENT,
    SEXUAL_CONTENT,
    HATE_SPEECH_OR_DISCRIMINATION,
    ABUSE_OR_HARASSMENT,
    VIOLENT_OR_DANGEROUS_CONTENT,
    PRIVACY_VIOLATION,
    ILLEGAL_INFORMATION,
}
