export const ROUTES = {
  ROOT: '/',
  SIGNUP: '/signup',
  LOGIN: '/login',
  COLLECTION_MYMOMENT: '/collection/my-moment',
  COLLECTION_MYCOMMENT: '/collection/my-comment',
  TODAY_MOMENT: '/today-moment',
  TODAY_MOMENT_EXTRA: '/today-moment-extra',
  TODAY_COMMENT: '/today-comment',
  TODAY_MOMENT_SUCCESS: '/today-moment/success',
  TODAY_COMMENT_SUCCESS: '/today-comment/success',
  GOOGLE_CALLBACK: '/auth/callback',
  MY: '/my',
  PASSWORD: '/password',
};
