export const ROUTES = {
  ROOT: '/',
  SIGNUP: '/signup',
  LOGIN: '/login',
  COLLECTION_MYMOMENT: '/collection/my-moment',
  COLLECTION_MYCOMMENT: '/collection/my-comment',
  TODAY_MOMENT: '/today-moment',
  TODAY_MOMENT_EXTRA: '/today-moment-extra',
  TODAY_COMMENT: '/today-comment',
  TODAY_MOMENT_SUCCESS: '/today-moment/success',
  GOOGLE_CALLBACK: '/auth/callback',
  MY: '/my',
  FIND_PASSWORD: '/find-password',
  NEW_PASSWORD: '/passwordUpdate',
  GROUPS: '/groups',
  GROUP_CREATE: '/groups/create',
  GROUP_DETAIL: '/groups/:groupId',
  GROUP_SETTINGS: '/groups/:groupId/settings',
  GROUP_MEMBERS: '/groups/:groupId/members',
  JOIN_GROUP: '/invite/:code',
};
