-- V1__Create_questions_table.sql (H2 전용이 필요할 경우)
CREATE TABLE questions (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   content VARCHAR(200) NOT NULL,
   question_type VARCHAR(50) NOT NULL,
   start_date DATE NOT NULL,
   end_date DATE NOT NULL,
   group_id BIGINT,

-- H2에서는 TIMESTAMP(6) 사용이 표준적입니다.
   created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
   deleted_at TIMESTAMP(6) NULL
);

CREATE INDEX idx_questions_lookup ON questions (start_date, question_type, group_id);