project:
  name: 2025-moment-server
  description: woowa-moment project server

review:
  auto_review: false
  review_on_push: false
  trigger: pull_request_only
  exclude:
    - "build/**"
    - ".gradle/**"
    - "out/**"
    - "logs/**"
  rules:
    - name: 코드 스타일
      enabled: true
    - name: Java 베스트 프랙티스
      enabled: true
    - name: Spring Boot 최적화
      enabled: true
    - name: JPA 사용법
      enabled: true
  summary: true
  path_instructions:
    - path: '**/*'
      instructions: |
        모든 리뷰 코멘트와 피드백을 한국어로 작성해주세요. 
        코드 리뷰 시 다음 사항들을 한국어로 설명해주세요:
        - 코드 개선 제안사항
        - 버그나 잠재적 문제점
        - 성능 최적화 방안 (예: N+1 쿼리 문제)
        - 코드 스타일 및 컨벤션 관련 피드백
        - Java 및 Spring Boot 관련 베스트 프랙티스

        기술적인 용어는 한국어와 영어를 병행 사용하되, 설명은 반드시 한국어로 해주세요.

llm:
  provider: gpt-4
  temperature: 0.2
