version: 0.0
os: linux

# CodeBuild 아티팩트(.zip)의 파일을 EC2 인스턴스의 어느 위치로 복사할지 정의
files:
  - source: / # .zip 파일의 최상위 경로 (discard-paths: yes 때문에 모든 파일이 여기 있음)
    destination: /home/ubuntu/moment/ # EC2 인스턴스에 배포할 애플리케이션 루트 디렉터리

# 배포 생명주기의 각 단계에서 실행할 스크립트를 지정
hooks:
  # ApplicationStart: 애플리케이션을 실제로 시작하는 가장 중요한 단계
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu

  # ValidateService: 애플리케이션이 성공적으로 시작되었는지 확인하는 단계
  # 이 훅이 성공해야 CodeDeploy는 배포를 '성공'으로 간주하고 ALB 트래픽을 전환함
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ubuntu
