ALTER TABLE users ADD COLUMN IF NOT EXISTS current_point INT NOT NULL DEFAULT 0;

ALTER TABLE users ADD COLUMN IF NOT EXISTS provider_type VARCHAR(20) NOT NULL DEFAULT 'EMAIL';

ALTER TABLE users DROP CONSTRAINT IF EXISTS uq_email;

ALTER TABLE users DROP CONSTRAINT IF EXISTS uq_email_provider;

ALTER TABLE users ADD CONSTRAINT uq_email_provider UNIQUE (email, provider_type);

ALTER TABLE users ADD COLUMN level VARCHAR(10) NOT NULL DEFAULT 'METEOR';
