name: Moment Client CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - develop
    paths:
      - 'client/**'

jobs:
  quality-check:
    name: Quality Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js with pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: 'client/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type Check
        run: pnpm tsc --noEmit

      - name: Lint Check
        run: pnpm lint

      - name: Format Check
        run: pnpm format:check

      - name: Run Tests
        run: pnpm test

      - name: Build Verification
        run: pnpm build
